# Generated by Django 3.1.13 on 2021-08-30 19:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dates_and_telephones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneanddate',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
