# Generated by Django 3.1.13 on 2021-08-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates_and_telephones', '0002_phoneanddate_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneanddate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneanddate',
            name='phone_number',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
